-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 21:10:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gospodarstwo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gospodarstwo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gospodarstwo` DEFAULT CHARACTER SET utf8 ;
USE `gospodarstwo` ;

-- -----------------------------------------------------
-- Table `gospodarstwo`.`uzytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`uzytkownik` (
  `id` INT NULL DEFAULT NULL,
  `kategoria` VARCHAR(50) NULL DEFAULT NULL,
  `typ` VARCHAR(50) NULL DEFAULT NULL,
  `ilosc_zadan` INT NULL DEFAULT NULL,
  `data_zatrudnienia` VARCHAR(45) NULL,
  `pesel` VARCHAR(11) NULL,
  `email` VARCHAR(45) NULL,
  `telefon` VARCHAR(9) NULL,
  `kompetencje` VARCHAR(255) NULL,
  `adres` VARCHAR(45) NULL,
  `kod_pocztowy` VARCHAR(6) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `gospodarstwo`.`zadanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`zadanie` (
  `id` INT NULL DEFAULT NULL,
  `tytul` VARCHAR(50) NULL DEFAULT NULL,
  `czas_rozpoczecia` DATETIME NULL DEFAULT NULL,
  `planowany_czas_zakonczenia` DATETIME NULL DEFAULT NULL,
  `faktyczny_czas_zakonczenia` DATETIME NULL DEFAULT NULL,
  `opis` TEXT NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `gospodarstwo`.`uzytkownik_zadanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`uzytkownik_zadanie` (
  `id` INT NULL DEFAULT NULL,
  `id_uzytkownika` INT NULL DEFAULT NULL,
  `id_zadania` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_uzytkownika` ASC) VISIBLE,
  INDEX (`id_zadania` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_uzytkownika`)
    REFERENCES `gospodarstwo`.`uzytkownik` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_zadania`)
    REFERENCES `gospodarstwo`.`zadanie` (`id`));


-- -----------------------------------------------------
-- Table `gospodarstwo`.`magazyn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`magazyn` (
  `id` INT NULL DEFAULT NULL,
  `nazwa_towaru` VARCHAR(50) NULL DEFAULT NULL,
  `ilosc_towaru` INT NULL DEFAULT NULL,
  `jednostka_miary` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `gospodarstwo`.`maszyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`maszyna` (
  `id` INT NULL DEFAULT NULL,
  `nazwa` VARCHAR(50) NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `stan` VARCHAR(50) NULL DEFAULT NULL,
  `przeglad` DATE NULL DEFAULT NULL,
  `data_zakupu` DATE NULL,
  `przebieg` INT NULL,
  `pojemnosc_zbiornika` VARCHAR(45) NULL,
  `rok_produkcji` VARCHAR(45) NULL,
  `opony` VARCHAR(45) NULL,
  `ilosc_koni` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `gospodarstwo`.`maszyna_zadanie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gospodarstwo`.`maszyna_zadanie` (
  `id` INT NULL DEFAULT NULL,
  `id_maszyny` INT NULL DEFAULT NULL,
  `id_zadania` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`id_maszyny` ASC) VISIBLE,
  INDEX (`id_zadania` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_maszyny`)
    REFERENCES `gospodarstwo`.`maszyna` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`id_zadania`)
    REFERENCES `gospodarstwo`.`zadanie` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
